# Working with Data 2: Pandas

**Pandas** is one of the most popular Python packages in data science: it makes **data
manipulation** and **data analysis** easy. Where NumPy gives us fast arrays, pandas gives us
**tables** — with named columns, mixed types and a toolbox of analysis methods.

In this lecture:

1. **Pandas data structures** — `Series` (one column) and `DataFrame` (a whole table).
2. **Reading data** — loading a real dataset (the Titanic passenger list) from a CSV file.
3. **Selecting data** — by position (`iloc`/`iat`), by label (`loc`/`at`), and by condition
   (boolean indexing).
4. **Aggregation** — descriptive statistics, counting categories, and `groupby`.
5. **Descriptive statistics on a second dataset** — fuel-economy data, correlations,
   top-N queries.

In [1]:
import pandas as pd   # the universal convention, like np for numpy

## 1. Pandas data structures

### Series — a single column

A `Series` stores data as a 1-D array — think of **one column** in a spreadsheet.
Note the index numbers pandas attaches on the left:

In [2]:
ser = pd.Series([5, 10, 15])

print("Data dimension:", ser.ndim)   # .ndim - number of dimensions
print("Data shape:", ser.shape)      # .shape - structure, like a NumPy array
ser

Data dimension: 1
Data shape: (3,)

0     5
1    10
2    15
dtype: int64

### DataFrame — a whole table

A `DataFrame` is several Series side by side — a table with rows and **named columns**,
looking exactly like a spreadsheet. One way to build one: a matrix of values plus a list of
column names:

In [3]:
df_columns = ["firstname", "surname", "age"]   # the column names

df_values = [                                  # the table body is just a matrix
    ["tanakrit", "saiphan", 17],
    ["nayos", "suwatano", 18],
    ["pannathorn", "krudthong", 18],
]

df = pd.DataFrame(columns=df_columns, data=df_values)
df

    firstname    surname  age
0    tanakrit    saiphan   17
1       nayos   suwatano   18
2  pannathorn  krudthong   18

Equivalently, build it from a dictionary — keys become column names, values become the
columns:

In [4]:
data = {
    "firstname": ["tanakrit", "mikey", "pannathorn"],
    "surname": ["saiphan", "suwatano", "krudthong"],
    "age": [17, 18, 18],
}

df = pd.DataFrame(data)
df   # same table as above

    firstname    surname  age
0    tanakrit    saiphan   17
1       mikey   suwatano   18
2  pannathorn  krudthong   18

## 2. Reading data from a file

In practice we rarely type DataFrames by hand — we **read** them from files. Pandas can read
CSV, JSON, Excel and many more formats
([full list here](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)).

We load the classic **Titanic** dataset — one row per passenger:

In [5]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

891 rows is too much to read at once. The first-look toolkit:

- `head(n)` — the first n rows (default 5);
- `tail(n)` — the last n rows;
- `sample(n)` — n random rows;
- `info()` — column names, types, and **how many values are missing**.

In [6]:
df.head(1)   # the very first row

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [7]:
df.tail(2)   # the last two rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
df.sample(2)   # two random rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
847,848,0,3,"Markoff, Mr. Marin",male,35.0,0,0,349213,7.8958,NaN,C
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.0,1,1,16966,134.5000,E34,C

In [9]:
df.info()   # column types and missing-value counts (look at Age and Cabin!)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

## 3. Selecting data by position or label

### Getting — plain indexing

A Series indexes like a list; a DataFrame sliced with a range of numbers returns those rows:

In [10]:
print(ser[1])    # one element of the Series
ser[0:2]         # a slice of the Series

10

0     5
1    10
dtype: int64

In [11]:
df[56:60]   # rows 56-59 of the DataFrame

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
56,57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,NaN,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,NaN,S
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9000,NaN,S

### Selecting by position: `iloc` and `iat`

`iloc[row, column]` selects by **integer position** — row and column numbers, both starting
at 0. `iat` is its faster single-value cousin (it requires *both* a row and a column, while
`iloc` can take just a row):

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
print(df.iloc[0, 3])   # row 0, column 3
print(df.iloc[2, 8])   # row 2, column 8
print(df.iat[0, 3])    # same as the first lookup, single-value access

Braund, Mr. Owen Harris
STON/O2. 3101282
Braund, Mr. Owen Harris

### Selecting by label: `loc` and `at`

`loc[row_label, column_name]` selects by **label** — here the row labels are the index
numbers and the column labels are the column names:

In [14]:
print(df.loc[0, "Name"])   # row 0, column "Name"
print(df.at[1, "Name"])    # row 1, column "Name" - single-value access

Braund, Mr. Owen Harris
Cumings, Mrs. John Bradley (Florence Briggs Thayer)

### Selecting subsets

Both `iloc` and `loc` extend naturally from single values to whole blocks of the table:

In [15]:
df.iloc[0]   # all of row 0 - one value per column

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [16]:
df.iloc[:, 5]   # every row, but only column 5

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [17]:
df.iloc[0:4]   # rows 0-3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [18]:
df.iloc[0:4, 0:4]   # rows 0-3, columns 0-3

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"

In [19]:
df.iloc[[0, 4], [0, 4]]   # exactly rows 0 and 4, columns 0 and 4

   PassengerId   Sex
0            1  male
4            5  male

In [20]:
df.loc[0:4]   # by label: rows 0-4 (note: loc INCLUDES the endpoint!)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
df.loc[0:2, "PassengerId":"Age"]   # rows 0-2, columns PassengerId through Age

,PassengerId,Survived,Pclass,Name,Sex,Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0

In [22]:
df.loc[0:4, ["PassengerId", "Age"]]   # rows 0-4, just these two columns

   PassengerId   Age
0            1  22.0
1            2  38.0
2            3  26.0
3            4  35.0
4            5  35.0

### Boolean indexing

The boolean-mask trick from NumPy works on tables too. A comparison applied to a Series or a
column produces `True`/`False` per row; indexing with that mask keeps only the `True` rows:

In [23]:
ser == 5   # which elements equal 5?

0     True
1    False
2    False
dtype: bool

In [24]:
print(ser[ser == 5])    # keep only the matching elements
print(ser[ser < 15])    # all elements below 15

0    5
dtype: int64
0     5
1    10
dtype: int64

The same idea finds all female passengers on the Titanic:

In [25]:
df["Sex"] == "male"   # one True/False per row

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [26]:
df[df["Sex"] == "female"]   # keep only the rows where the mask is True

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

## 4. Aggregation

**Aggregating** summarises many rows into a few numbers — means, maxima, minima, most frequent
values, and so on. First we narrow the table to the columns of interest:

In [27]:
df2 = df[["PassengerId", "Sex", "Age", "Ticket", "Fare"]]   # whole table, chosen columns
df2.head()

   PassengerId     Sex   Age            Ticket     Fare
0            1    male  22.0         A/5 21171   7.2500
1            2  female  38.0          PC 17599  71.2833
2            3  female  26.0  STON/O2. 3101282   7.9250
3            4  female  35.0            113803  53.1000
4            5    male  35.0            373450   8.0500

In [28]:
df2.dtypes   # what type is each column?

PassengerId      int64
Sex                str
Age            float64
Ticket             str
Fare           float64
dtype: object

### Numerical data

For descriptive statistics we can call individual functions — or `describe()` for everything
at once: mean, standard deviation, min, max and percentiles.

In [29]:
print(f"Youngest passenger: {df2['Age'].min()}")
print(f"Oldest passenger:   {df2['Age'].max()}")
print(f"Average age:        {df2['Age'].mean()}")
print(f"Median age:         {df2['Age'].median()}")

Youngest passenger: 0.42
Oldest passenger:   80.0
Average age:        29.69911764705882
Median age:         28.0

In [30]:
df2.describe()   # all of the above (and more) in one call

       PassengerId         Age        Fare
count   891.000000  714.000000  891.000000
mean    446.000000   29.699118   32.204208
std     257.353842   14.526497   49.693429
min       1.000000    0.420000    0.000000
25%     223.500000   20.125000    7.910400
50%     446.000000   28.000000   14.454200
75%     668.500000   38.000000   31.000000
max     891.000000   80.000000  512.329200

### Categorical data

For category-like columns we ask different questions: what distinct values exist (`unique`),
how many distinct values (`nunique`), and how often each occurs (`value_counts`):

In [31]:
df["Ticket"].unique()   # the distinct ticket codes (no repeats)

<StringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',
 ...
           '349212',           '349217',           '349257',
             '7552', 'C.A./SOTON 34068',  'SOTON/OQ 392076',
           '211536',           '112053',           '111369',
           '370376']
Length: 681, dtype: str

In [32]:
df["Ticket"].nunique()   # how many distinct values

681

In [33]:
df["Ticket"].value_counts()   # how often each value occurs

Ticket
347082             7
1601               7
CA. 2343           7
3101295            6
CA 2144            6
                  ..
SOTON/OQ 392076    1
211536             1
112053             1
111369             1
370376             1
Name: count, Length: 681, dtype: int64

### Categorical × numerical: `groupby`

`groupby()` splits the table into groups by category, applies a statistic per group, and
combines the results
([split-apply-combine](https://pandas.pydata.org/docs/user_guide/groupby.html)).
The oldest, youngest and average passenger — separately for each sex:

In [34]:
df2.groupby(["Sex"])["Age"].max()    # oldest passenger per group

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

In [35]:
df2.groupby(["Sex"])["Age"].min()    # youngest per group

Sex
female    0.75
male      0.42
Name: Age, dtype: float64

In [36]:
df2.groupby(["Sex"])["Age"].mean()   # average age per group

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [37]:
df2.groupby(["Sex"])["Fare"].mean()  # average ticket fare per group

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

## 5. Descriptive statistics on a second dataset

Let's put the whole toolkit to work on a fresh dataset: fuel-economy figures for 234 cars
(`mpg`). Same first-look routine as before:

In [38]:
mpg = pd.read_csv("https://raw.githubusercontent.com/prasertcbs/tutorial/master/mpg.csv")
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [39]:
print(mpg.shape)   # (rows, columns)
mpg.info()

(234, 11)
<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    str
 1   model         234 non-null    str
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    str
 6   drv           234 non-null    str
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    str
 10  class         234 non-null    str
dtypes: float64(1), int64(4), str(6)
memory usage: 20.2 KB

The table mixes text and number columns, so for table-wide statistics we pass
`numeric_only=True` — averaging a manufacturer name makes no sense:

In [40]:
mpg.mean(numeric_only=True)     # column averages

displ       3.471795
year     2003.500000
cyl         5.888889
cty        16.858974
hwy        23.440171
dtype: float64

In [41]:
mpg.median(numeric_only=True)   # column medians

displ       3.3
year     2003.5
cyl         6.0
cty        17.0
hwy        24.0
dtype: float64

Counting categories: how many models per manufacturer, and per vehicle class? Note that
`mpg.class` would be a **syntax error** — `class` is a Python keyword — so bracket notation
`mpg["class"]` is required for this column:

In [42]:
mpg.manufacturer.value_counts()   # dot notation works for ordinary column names

manufacturer
dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: count, dtype: int64

In [43]:
mpg["class"].value_counts()   # bracket notation - "class" clashes with the keyword

class
suv           62
compact       47
midsize       41
subcompact    35
pickup        33
minivan       11
2seater        5
Name: count, dtype: int64

`describe()` again — and a trick: transposing it with `.T` puts one **row per column**,
which is much easier to scan when there are many columns:

In [44]:
mpg.describe()

            displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

In [45]:
mpg.describe().T   # transposed: one row per column

       count         mean       std     min     25%     50%     75%     max
displ  234.0     3.471795  1.291959     1.6     2.4     3.3     4.6     7.0
year   234.0  2003.500000  4.509646  1999.0  1999.0  2003.5  2008.0  2008.0
cyl    234.0     5.888889  1.611534     4.0     4.0     6.0     8.0     8.0
cty    234.0    16.858974  4.255946     9.0    14.0    17.0    19.0    35.0
hwy    234.0    23.440171  5.954643    12.0    18.0    24.0    27.0    44.0

### Correlation

`corr()` measures how strongly each pair of numeric columns moves together:
**+1** = perfectly proportional, **−1** = perfectly inversely proportional, **0** = no
relationship. City and highway fuel economy, unsurprisingly, are strongly correlated:

In [46]:
mpg.corr(numeric_only=True)

          displ      year       cyl       cty       hwy
displ  1.000000  0.147843  0.930227 -0.798524 -0.766020
year   0.147843  1.000000  0.122245 -0.037232  0.002158
cyl    0.930227  0.122245  1.000000 -0.805771 -0.761912
cty   -0.798524 -0.037232 -0.805771  1.000000  0.955916
hwy   -0.766020  0.002158 -0.761912  0.955916  1.000000

### Top-N queries

`nlargest` / `nsmallest` sort by a column and keep the extremes — the 5 most fuel-efficient
cars in the city, and the 5 thirstiest on the highway:

In [47]:
mpg.nlargest(5, columns="cty")    # top 5 by city fuel economy

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
221,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact
212,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact
222,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact
99,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact
196,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact

In [48]:
mpg.nsmallest(5, columns="hwy")   # bottom 5 by highway fuel economy

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
54,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup
59,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv
65,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup
69,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup
126,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv

## Summary

| Task | Function / syntax |
|---|---|
| One column / whole table | `pd.Series([...])` / `pd.DataFrame(dict)` |
| Load a file | `pd.read_csv(path_or_url)` |
| First look | `head`, `tail`, `sample`, `info`, `shape`, `dtypes` |
| Select by position | `df.iloc[rows, cols]`, `df.iat[r, c]` |
| Select by label | `df.loc[rows, "col_a":"col_b"]`, `df.at[r, "col"]` |
| Filter by condition | `df[df["col"] == value]` |
| Summary statistics | `mean`, `median`, `min`, `max`, `describe()` |
| Categories | `unique`, `nunique`, `value_counts` |
| Per-group statistics | `df.groupby("cat")["num"].mean()` |
| Relationships / extremes | `corr(numeric_only=True)`, `nlargest`, `nsmallest` |

**Key takeaways**

- A DataFrame is a spreadsheet you can program: Series = column, DataFrame = table.
- Always start with `head()` + `info()` — know your columns, types and missing values
  before computing anything.
- `iloc` selects by *position*, `loc` by *label* — and `loc` slices **include** the endpoint.
- Boolean masks carry over from NumPy and are the main way to filter rows.
- `groupby` answers "statistic X per category Y" in a single line.

**Exercises**

1. From the Titanic table, select the names and ages of the first 10 passengers using `loc`.
2. How many passengers were under 18? (Boolean mask + `len` or `.shape`.)
3. What is the average fare per passenger class (`Pclass`)? Does it match your intuition?
4. In the mpg dataset, which manufacturer has the best **average** city fuel economy?
   (`groupby` + `mean` + `nlargest`.)
5. Use a boolean mask to list all cars with `cty > 25`, then check which classes they belong to.